[workspace]
members = ["apps/*", "crates/*"]
exclude = ["apps/daemon"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[workspace.dependencies]
# local crates
daemon-client = { path = "./crates/daemon-client", version = "0.0.0" }
